CREATE TYPE "ImportLineStatus" AS ENUM ('PENDING', 'APPLIED', 'FAILED');

ALTER TYPE "FileRelatedType" ADD VALUE IF NOT EXISTS 'DOCUMENT';
ALTER TYPE "FileRelatedType" ADD VALUE IF NOT EXISTS 'MEETING';
ALTER TYPE "FileRelatedType" ADD VALUE IF NOT EXISTS 'MEETING_MINUTES';

ALTER TABLE "DUES_IMPORT_LINES"
  ADD COLUMN "source_unit_id" TEXT,
  ADD COLUMN "period_month" DATE,
  ADD COLUMN "due_date" DATE,
  ADD COLUMN "paid_date" DATE,
  ADD COLUMN "row_status" "ImportLineStatus" NOT NULL DEFAULT 'PENDING',
  ADD COLUMN "error_reason" TEXT;

ALTER TABLE "DUES_IMPORT_LINES"
  ALTER COLUMN "unit_id" DROP NOT NULL,
  ALTER COLUMN "amount" DROP NOT NULL,
  ALTER COLUMN "status" DROP NOT NULL;

ALTER TABLE "DUES_IMPORT_LINES"
  DROP CONSTRAINT IF EXISTS "DUES_IMPORT_LINES_unit_id_fkey";

ALTER TABLE "DUES_IMPORT_LINES"
  ADD CONSTRAINT "DUES_IMPORT_LINES_unit_id_fkey"
  FOREIGN KEY ("unit_id") REFERENCES "UNITS"("unit_id")
  ON DELETE RESTRICT
  ON UPDATE CASCADE;

CREATE INDEX "DUES_IMPORT_LINES_row_status_idx"
  ON "DUES_IMPORT_LINES"("row_status");
